### ISSUE TITLE
Still in beta

### ISSUE THREAD

**Issue by BenLune** [netlify/angular-runtime#59]
Hi,
I plan to host Angular Universal projects in my Netlify account. I see this project, still in beta after one year.
Angular is working hard to improve SSR with non destructive hydration (https://angular.io/guide/roadmap#explore-hydration-and-server-side-rendering-usability-improvements). I think many people will be back interesting into it.
Please let me know about your plans.
Thanks,
Benoît

**Comment by BenLune** [comment]
ok

**Comment by Skn0tt** [comment]
Please excuse the late reply - better late than never they say, I guess. We've released v2 of this project a couple moons ago, and it's not in beta anymore!
