### ISSUE TITLE
Angular 17 `browser` builder is not supported

### ISSUE THREAD

**Issue by sonallux** [netlify/angular-runtime#86]
**Describe the bug**
I am currently still using the `browser` builder with Angular 17. Unfortunately, the new Netlify Angular Runtime only supports the new `application` builder. So when deploying an Angular 17 app with the `browser` builder the following error message is show on the Netlify UI:

```
5:20:14 PM: Configuration error                                           
5:20:14 PM: ────────────────────────────────────────────────────────────────
5:20:14 PM: ​
5:20:14 PM:   Error message
5:20:14 PM:   Deploy did not succeed: Deploy directory "dist/angular-music/browser" does not exist
```

**To Reproduce**
1. Create an Angular 17 app
2. Switch to the old `browser` builder
3. Deploy the app with netlify
4. See this Error in the deploying step: `Error message: Deploy did not succeed: Deploy directory "dist/angular-music/browser" does not exist`

**Expected behavior**
I can deploy an Angular 17 app with the `browser` builder to Netlify

**Versions**
- Angular: 17.0.4
- plugin (if installed in your package.json at fixed version):

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]
 - netlify/cli version: 

**If you're using file-based installation**
- netlify.toml:

**Comment by mariusbolik** [comment]
Seems like that's this package is also for Angular Universal. If the runtime is removed in the Site Settings, the deployment works. This package should definitely be adapted. More info in my comment in the Netlify forum: https://answers.netlify.com/t/angular-deployment-issue/106276/23?u=mariusbolik

**Comment by Skn0tt** [comment]
I believe this should be fixed by https://github.com/netlify/angular-runtime/pull/94. Working on releasing that now!

**Comment by Skn0tt** [comment]
The fix was published as under https://github.com/netlify/angular-runtime/releases/tag/v2.0.5. I'll work on rolling that out to Netlify now!

**Comment by Skn0tt** [comment]
> I'll work on rolling that out to Netlify now!

Done! Could y'all double-check if this fixed the issue on your end? If you installed the runtime via `package.json`, then you'll need to update to the new version. If the runtime was auto-installed for you via the Netlify UI, then https://github.com/netlify/plugins/pull/1304 should've rolled it out automatically for you.

**Comment by Skn0tt** [comment]
I'll go ahead and close this, happy to reopen if you encounter other issues with this!
